// Code generated by togo. DO NOT EDIT.
//
// Installed plugins are blank-imported here so their init() registers them
// with the kernel for auto-discovery. Managed by `togo install`.
package plugins

import (
	_ "github.com/togo-framework/auth"
	_ "github.com/togo-framework/auth-dev"
	_ "github.com/togo-framework/autopilot"
	_ "github.com/togo-framework/cache"
	_ "github.com/togo-framework/data"
	_ "github.com/togo-framework/i18n"
	_ "github.com/togo-framework/notification-center"
	_ "github.com/togo-framework/os"
	_ "github.com/togo-framework/os-example/plugins/notes"
	_ "github.com/togo-framework/os-example/plugins/prefs"
	_ "github.com/togo-framework/os-example/plugins/weather"
	_ "github.com/togo-framework/plugin-host"
	_ "github.com/togo-framework/queue"
	_ "github.com/togo-framework/realtime"
	_ "github.com/togo-framework/settings"
	_ "github.com/togo-framework/storage"
)
